"""
Generates the ANCHOR-Net stub model and its golden vectors.

This is THE source of truth for the model input/output contract between
the ML/backend track and the Android/on-device track. Nobody hand-writes
the ONNX file or the manifest — both are generated by this script, so the
two can never drift apart by a typo.

Run this once now (stub weights) to unblock the Android side on day 1.
Re-run it (unchanged interface, real trained weights) when the real
model is ready — same script, same contract, different weight values.

Usage:
    python generate_stub_model.py

Outputs (all committed to git):
    anchor_net_stub.onnx        - the model graph + weights
    model_manifest.json         - machine-readable I/O contract, embedded
                                   into the ONNX file's metadata_props too
    golden_vectors/*.json       - fixed (input -> exact output) pairs used
                                   by BOTH the Python test suite and the
                                   Android instrumented test to prove the
                                   exported model runs identically on
                                   ONNX Runtime Mobile as it does here.
"""

import json
import hashlib
from pathlib import Path

import numpy as np
import onnx
from onnx import helper, numpy_helper, TensorProto

HERE = Path(__file__).parent

# ---------------------------------------------------------------------------
# THE CONTRACT — change these values only with agreement from both tracks,
# and bump CONTRACT_VERSION when you do (see ../VERSIONING.md).
# ---------------------------------------------------------------------------

CONTRACT_VERSION = "1.0.0"

WINDOW_SIZE_SAMPLES = 20        # 2.0 s at 10 Hz, per PRD §14 windowing
SAMPLE_RATE_HZ = 10

# Order matters. This exact order, these exact names. Nothing is inferred
# from column position anywhere downstream — both sides read this list.
#
# GRAVITY / FRAME, READ THIS: accel_x/y/z here is LINEAR acceleration
# (gravity REMOVED: linear = raw_accel - gravity_channel) in VEHICLE frame
# (ISO 8855-style: x=forward, y=left, z=up), NOT the raw phone-frame,
# gravity-inclusive signal you get straight off a sensor or out of
# contracts/replay_csv/sample_replay.csv. At rest, accel_z here is ~0, not
# ~9.8. Full pipeline (raw log -> this tensor) and the exact rotation math
# are frozen in ../frame_convention.md — read it before wiring up either
# a training input pipeline or an on-device inference/replay path.
FEATURE_ORDER = [
    "accel_x", "accel_y", "accel_z",   # m/s^2, vehicle-frame, GRAVITY REMOVED (linear accel)
    "gyro_x", "gyro_y", "gyro_z",      # rad/s, vehicle-frame
]
NUM_FEATURES = len(FEATURE_ORDER)

INPUT_NAME = "imu_window"
INPUT_SHAPE = [1, WINDOW_SIZE_SAMPLES, NUM_FEATURES]   # [batch, time, features]

# Output semantics — read this, do not guess it:
#   velocity_mean_mps    : predicted forward speed for this window, m/s, float32
#   velocity_log_variance: log(variance), NOT variance and NOT std-dev.
#                           Filter side must do variance = exp(log_variance).
#                           Log-space avoids the model ever emitting a
#                           negative variance, which is a real failure mode
#                           if you regress variance directly.
OUTPUT_MEAN_NAME = "velocity_mean_mps"
OUTPUT_LOGVAR_NAME = "velocity_log_variance"

# Placeholder normalization stats. THE REAL TRAINING RUN MUST REPLACE THESE
# and re-run this script — do not hand-edit them separately anywhere else.
# Any consumer must apply (x - mean) / std to raw features BEFORE inference,
# using exactly these arrays, because they are baked into what the weights
# below were "trained" (here: initialized) against.
NORM_MEAN = np.zeros(NUM_FEATURES, dtype=np.float32)
NORM_STD = np.ones(NUM_FEATURES, dtype=np.float32)


def build_model() -> onnx.ModelProto:
    rng = np.random.default_rng(seed=42)

    flat_dim = WINDOW_SIZE_SAMPLES * NUM_FEATURES

    # A trivial two-head linear "network" — enough to prove the plumbing,
    # not meant to predict anything real. Real training replaces the
    # weight values only; the graph shape below IS the contract.
    w_mean = rng.normal(0, 0.01, (flat_dim, 1)).astype(np.float32)
    b_mean = np.zeros((1,), dtype=np.float32)
    w_logvar = rng.normal(0, 0.01, (flat_dim, 1)).astype(np.float32)
    b_logvar = np.full((1,), -1.0, dtype=np.float32)  # start at a plausible small variance

    input_tensor = helper.make_tensor_value_info(
        INPUT_NAME, TensorProto.FLOAT, INPUT_SHAPE
    )
    mean_out = helper.make_tensor_value_info(
        OUTPUT_MEAN_NAME, TensorProto.FLOAT, [1, 1]
    )
    logvar_out = helper.make_tensor_value_info(
        OUTPUT_LOGVAR_NAME, TensorProto.FLOAT, [1, 1]
    )

    initializers = [
        numpy_helper.from_array(np.array([1, flat_dim], dtype=np.int64), name="flat_shape"),
        numpy_helper.from_array(w_mean, name="w_mean"),
        numpy_helper.from_array(b_mean, name="b_mean"),
        numpy_helper.from_array(w_logvar, name="w_logvar"),
        numpy_helper.from_array(b_logvar, name="b_logvar"),
    ]

    nodes = [
        helper.make_node("Reshape", [INPUT_NAME, "flat_shape"], ["flat"]),
        helper.make_node("Gemm", ["flat", "w_mean", "b_mean"], [OUTPUT_MEAN_NAME]),
        helper.make_node("Gemm", ["flat", "w_logvar", "b_logvar"], [OUTPUT_LOGVAR_NAME]),
    ]

    graph = helper.make_graph(
        nodes,
        "anchor_net_stub",
        [input_tensor],
        [mean_out, logvar_out],
        initializer=initializers,
    )

    # Pin the opset explicitly. This number is part of the contract:
    # ONNX Runtime Mobile on the Android side must be a version that
    # supports this opset. See ../VERSIONING.md for the pinned pair.
    opset = helper.make_opsetid("", 17)
    model = helper.make_model(graph, opset_imports=[opset], producer_name="anchor-net-training")
    model.ir_version = 9

    # Embed the contract INSIDE the file, so the Android side can sanity-check
    # the file it loaded against what it expects, and mismatches fail loudly
    # at model-load time instead of producing silently-wrong numbers.
    metadata = {
        "contract_version": CONTRACT_VERSION,
        "window_size_samples": str(WINDOW_SIZE_SAMPLES),
        "sample_rate_hz": str(SAMPLE_RATE_HZ),
        "feature_order": ",".join(FEATURE_ORDER),
        "output_mean_name": OUTPUT_MEAN_NAME,
        "output_logvar_name": OUTPUT_LOGVAR_NAME,
        "output_semantics": "mean=m/s, logvar=natural-log(variance); do variance=exp(logvar)",
        "input_frame_convention": "vehicle-frame (x=fwd,y=left,z=up), gravity REMOVED (linear accel) — NOT raw phone-frame gravity-inclusive; see ../frame_convention.md",
        "norm_mean": ",".join(str(x) for x in NORM_MEAN),
        "norm_std": ",".join(str(x) for x in NORM_STD),
    }
    for k, v in metadata.items():
        entry = model.metadata_props.add()
        entry.key = k
        entry.value = v

    onnx.checker.check_model(model)
    return model


def make_deterministic_inputs():
    """A handful of fixed, named input windows used for golden-vector testing."""
    cases = {}

    zeros = np.zeros(INPUT_SHAPE, dtype=np.float32)
    cases["stationary"] = zeros  # vehicle at rest: all-zero accel/gyro window

    ramp = np.zeros(INPUT_SHAPE, dtype=np.float32)
    for t in range(WINDOW_SIZE_SAMPLES):
        ramp[0, t, 0] = 0.1 * t          # accel_x ramps up
        ramp[0, t, 3] = 0.01             # small constant yaw rate
    cases["accelerating_straight"] = ramp

    rng = np.random.default_rng(seed=7)
    cases["random_vibration"] = rng.normal(0, 0.5, INPUT_SHAPE).astype(np.float32)

    return cases


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def main():
    import onnxruntime as ort

    model = build_model()
    onnx_path = HERE / "anchor_net_stub.onnx"
    onnx.save(model, str(onnx_path))
    print(f"wrote {onnx_path}")

    session = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])

    golden_dir = HERE / "golden_vectors"
    golden_dir.mkdir(exist_ok=True)
    for name, arr in make_deterministic_inputs().items():
        outputs = session.run(
            [OUTPUT_MEAN_NAME, OUTPUT_LOGVAR_NAME], {INPUT_NAME: arr}
        )
        mean_val = float(outputs[0][0][0])
        logvar_val = float(outputs[1][0][0])
        vector = {
            "name": name,
            "contract_version": CONTRACT_VERSION,
            "input": arr[0].tolist(),  # [window, features], batch dim dropped for readability
            "expected_output": {
                OUTPUT_MEAN_NAME: mean_val,
                OUTPUT_LOGVAR_NAME: logvar_val,
            },
            "tolerance_abs": 1e-4,
            "note": (
                "Load anchor_net_stub.onnx, run inference on `input` reshaped to "
                f"{INPUT_SHAPE}, and assert both outputs match expected_output "
                "within tolerance_abs. This is the cross-language proof that the "
                "ONNX Runtime build on Android reproduces the same numbers as "
                "onnxruntime does here in Python."
            ),
        }
        out_path = golden_dir / f"{name}.json"
        out_path.write_text(json.dumps(vector, indent=2))
        print(f"wrote {out_path}  mean={mean_val:.6f} logvar={logvar_val:.6f}")

    manifest = {
        "contract_version": CONTRACT_VERSION,
        "model_file": "anchor_net_stub.onnx",
        "model_sha256": sha256_of(onnx_path),
        "onnx_opset": 17,
        "window_size_samples": WINDOW_SIZE_SAMPLES,
        "sample_rate_hz": SAMPLE_RATE_HZ,
        "input_name": INPUT_NAME,
        "input_shape": INPUT_SHAPE,
        "feature_order": FEATURE_ORDER,
        "feature_units": {
            "accel_x": "m/s^2", "accel_y": "m/s^2", "accel_z": "m/s^2",
            "gyro_x": "rad/s", "gyro_y": "rad/s", "gyro_z": "rad/s",
        },
        "normalization": {
            "applied_by": "caller, before inference",
            "formula": "(raw - mean) / std, per-feature",
            "mean": NORM_MEAN.tolist(),
            "std": NORM_STD.tolist(),
        },
        "outputs": {
            OUTPUT_MEAN_NAME: {"shape": [1, 1], "unit": "m/s", "meaning": "predicted forward speed for this window"},
            OUTPUT_LOGVAR_NAME: {"shape": [1, 1], "unit": "log((m/s)^2)", "meaning": "natural-log of predicted variance; consumer computes variance = exp(this) and MUST NOT treat this value as variance or std directly"},
        },
        "golden_vectors_dir": "golden_vectors/",
        "compatibility_rule": (
            "The Android app declares MIN_SUPPORTED_CONTRACT_VERSION. If a "
            "downloaded model's contract_version (read from this manifest, or "
            "from the ONNX metadata_props embedded in the file itself) is not "
            "semver-compatible, the app MUST refuse to load it and fall back "
            "per FR-24 (model-failure fallback), never attempt to run it anyway."
        ),
    }
    manifest_path = HERE / "model_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"wrote {manifest_path}")


if __name__ == "__main__":
    main()
